events {}

http {
	server {
		listen 443 ssl;
		ssl_certificate /etc/nginx/certs/nginx.crt;
		ssl_certificate_key /etc/nginx/certs/nginx.key;

		location ~ \.php$ {
			try_files $uri =404;
			fastcgi_index index.php;
			fastcgi_pass wordpress:9000;
		}

	}
}
