version: '3'

services:

  nginx:
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERTS_=${CERTS_}
    volumes:
      - wordpress-data:/wordpress
    networks:
      - default
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
    volumes:
      - type: bind
        source: /home/noah/data/wordpress
        target: /wordpress
    networks:
      - default
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - default
    restart: always

  adminer:
    image: adminer
    networks:
      - default
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: always

  static:
    build:
      context: requirements/static
    networks:
      - default
    ports:
      - 80:80
    restart: always

  ftp:
    build:
      context: requirements/ftp
    networks:
      - default
    ports:
      - 21:21
    depends_on:
      - wordpress
    restart: always

  deno:
    build:
      context: requirements/deno
    networks:
      - default
    ports:
      - 8000:8000
    restart: always

volumes:

  wordpress-data:
    driver_opts:
      o: bind

  mariadb-data:
    driver_opts:
      o: bind

networks:
  default:
    driver: bridge
