version: '3'

services:

  nginx:
    build: requirements/nginx
    networks: [ default ]
    ports: [ 443:443 ]
    volumes: [ public:/wordpress ]
    depends_on: [ wordpress ]
    restart: always

  wordpress:
    build: requirements/wordpress
    networks: [ default ]
    volumes: [ public:/wordpress ]
    restart: always

  mariadb:
    build: requirements/mariadb
    networks: [ default ]
    restart: always

  adminer:
    image: adminer
    networks: [ default ]
    ports: [ 8080:8080 ]
    depends_on: [ mariadb ]
    restart: always

volumes:
  public:

networks:
  default:
    driver: bridge
