version: '3'

services:

  nginx:
    build: requirements/nginx
    networks: [ default ]
    ports: [ 443:443 ]
    volumes: [ wordpress-data:/wordpress ]
    depends_on: [ wordpress ]
    env_file: [ .env ]
    restart: always

  wordpress:
    build: requirements/wordpress
    networks: [ default ]
    volumes: [ wordpress-data:/wordpress ]
    restart: always

  mariadb:
    build: requirements/mariadb
    networks: [ default ]
    volumes: [ mariadb-data:/var/lib/mysql ]
    env_file: [ .env ]
    restart: always

  adminer:
    image: adminer
    networks: [ default ]
    ports: [ 8080:8080 ]
    depends_on: [ mariadb ]
    restart: always

  static:
    build: requirements/static
    networks: [ default ]
    ports: [ 80:80 ]
    env_file: [ .env ]
    restart: always

  ftp:
    build: requirements/ftp
    networks: [ default ]
    ports: [ 21:21 ]
    volumes: [ wordpress-data:/wordpress ]
    depends_on: [ wordpress ]
    restart: always

volumes:

  wordpress-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  mariadb-data:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  default:
    driver: bridge
