version: '3'

services:

  nginx:
    build: requirements/nginx
    networks: [ default ]
    ports: [ 443:443 ]
    volumes: [ ~/data/wordpress:/wordpress ]
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on: [ wordpress ]
    restart: always

  wordpress:
    build: requirements/wordpress
    networks: [ default ]
    volumes: [ ~/data/wordpress:/wordpress ]
    restart: always

  mariadb:
    build: requirements/mariadb
    networks: [ default ]
    volumes: [ ~/data/mariadb:/var/lib/mysql ]
    restart: always

  adminer:
    image: adminer
    networks: [ default ]
    ports: [ 8080:8080 ]
    depends_on: [ mariadb ]
    restart: always

  static:
    build: requirements/static
    networks: [ default ]
    ports: [ 80:80 ]
    restart: always

  ftp:
    build: requirements/ftp
    networks: [ default ]
    ports: [ 21:21 ]
    volumes: [ ~/data/wordpress:/wordpress ]
    depends_on: [ wordpress ]
    restart: always

  deno:
    build: requirements/deno
    networks: [ default ]
    ports: [ 8000:8000 ]
    restart: always

networks:
  default:
    driver: bridge
